### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by asimon655** [gauthamp10/freedownloadmanager-linux-appimage#1]
im following the instructions on my fedora 34.

when im running the pkg2appimage its finding all the dependencies, but stops when trying to download a .yml file.

i checked the link and its broken and returning 404 error.

this is the last line the log (and the broken link)

`+ wget -q https://github.com/AppImage/AppImages/raw/master/recipes/recipes/freedownloadmanager.yml.yml -O /tmp/_recipe.yml`

i also couldnt find any file under that name in that repository.

i hope it has a simple solution, if its complex im planning anyway to migrate to arch

**Comment by gauthamp10** [comment]
I think pkg2appimage updated something which had broken the process. Let me check

**Comment by gauthamp10** [comment]
> im following the instructions on my fedora 34.
> 
> when im running the pkg2appimage its finding all the dependencies, but stops when trying to download a .yml file.
> 
> i checked the link and its broken and returning 404 error.
> 
> this is the last line the log (and the broken link)
> 
> `+ wget -q https://github.com/AppImage/AppImages/raw/master/recipes/recipes/freedownloadmanager.yml.yml -O /tmp/_recipe.yml`
> 
> i also couldnt find any file under that name in that repository.
> 
> i hope it has a simple solution, if its complex im planning anyway to migrate to arch

It was my mistake!. A typo in the recipe file name. It's fixed now. Thanks for pointing out.
